'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_REQUEST = exports.GET_REQUEST = 'GET_REQUEST';
var GET_REQUEST_PL = exports.GET_REQUEST_PL = 'GET_REQUEST_PL';
var PUT_REQUEST = exports.PUT_REQUEST = 'PUT_REQUEST';
var DELETE_REQUEST = exports.DELETE_REQUEST = 'DELETE_REQUEST';
var POST_REQUEST = exports.POST_REQUEST = 'POST_REQUEST';
var RECEIVE_API_DATA_PDV_DATA = exports.RECEIVE_API_DATA_PDV_DATA = 'RECEIVE_API_DATA_PDV_DATA';
var CHANGE_SUBMIT_VALIDATION = exports.CHANGE_SUBMIT_VALIDATION = 'CHANGE_SUBMIT_VALIDATION';
var DROP_DOWN_CHANGE = exports.DROP_DOWN_CHANGE = 'DROP_DOWN_CHANGE';
var SET_UPDATE_DATA = exports.SET_UPDATE_DATA = 'SET_UPDATE_DATA';